config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  resources :uploads

  match "/uploads/import" => "uploads#import", via: :post

  root 'uploads#index'

end

app/models/upload.rb
class Upload < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  include CSVUpload

  def new
    @upload = Upload.new
    end

    def create
  	@upload = Upload.new(import_params)
  	if @upload.save
  		redirect_to root_url
		end
	end

  def show
  	@upload = Upload.find(params[:id])
  end

  def index
  	@uploads = Upload.all
  end

  def import
    csv_separate(params[:file].tempfile, params[:parent_keyword], params[:keywords])
    redirect_to root_url
  end

  private

  def set_upload
    @upload = Upload.find(params[:id])
  end

  def	import_params
  	params.require(:file).permit(:first_name, :last_name, :email, :company, :religion, :title, :city, :street, :state, :zip, :phone, :web_site, :revenue, :employees)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/Uploads/index.html.erb
<%= flash[:notice] %>
<tbody>
	<% @uploads.each do |upload| %>
		<tr>
			<td><%= upload.name %></td>
		</tr>
	<% end %>
</tbody>
	
<div>
	<%= link_to 'New Upload', new_upload_path %>
</div>

app/views/Uploads/new.html.erb
<div>
  <h1>Import a CSV File</h1>
  <%= form_tag({action: "import"}, multipart: true) do %>
  	<h3>Column</h3>
  	<%= select_tag ("parent_keyword"), options_for_select(["first name", "last name", "email", "company", "religious", "title", "street", "city", "state", "zip code", "phone", "web address", "revenue", "employees" ]) %>
  	<h3>Keywords</h3>
  	<%= text_field_tag("keywords") %>
    <%= file_field_tag("file") %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsvListSeparating</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>